spring.application.name=springboot-mybatis-quickstart

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.url=jdbc:mysql://localhost:3306/web01
spring.datasource.username=root
spring.datasource.password=Root123!@#

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
